services:
  mariadb:
    image: mariadb:11.2.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: traffic_sign_observations
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
  backend:
    depends_on:
      - mariadb
    env_file: backend/.env
    image: backend
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: backend/Dockerfile
  frontend:
    depends_on:
      - backend
    image: frontend
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: frontend/Dockerfile
