CREATE DATABASE IF NOT EXISTS traffic_sign_observations;

USE traffic_sign_observations;

DROP TABLE IF EXISTS Traffic_Sign_Observation;
DROP TABLE IF EXISTS Observation_Cluster;
DROP TABLE IF EXISTS Observation_Type;

CREATE TABLE Observation_Type
(
    OBSERVATION_TYPE_ID BIGINT              NOT NULL AUTO_INCREMENT,
    OBSERVATION_TYPE    VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (OBSERVATION_TYPE_ID)
);

CREATE TABLE Observation_Cluster
(
    OBSERVATION_CLUSTER_ID BIGINT NOT NULL AUTO_INCREMENT,
    OBSERVATION_TYPE_ID    BIGINT NOT NULL,
    VALUE                  VARCHAR(255),
    RADIUS                 INT    NOT NULL,
    PRIMARY KEY (OBSERVATION_CLUSTER_ID),
    FOREIGN KEY (OBSERVATION_TYPE_ID) REFERENCES Observation_Type (OBSERVATION_TYPE_ID)
);

CREATE TABLE Traffic_Sign_Observation
(
    TRAFFIC_SIGN_OBSERVATION_ID BIGINT NOT NULL AUTO_INCREMENT,
    LATITUDE                    DOUBLE NOT NULL,
    LONGITUDE                   DOUBLE NOT NULL,
    HEADING                     INT    NOT NULL,
    OBSERVATION_TYPE_ID         BIGINT NOT NULL,
    VALUE                       VARCHAR(255),
    OBSERVATION_CLUSTER_ID      BIGINT NOT NULL,
    PRIMARY KEY (TRAFFIC_SIGN_OBSERVATION_ID),
    FOREIGN KEY (OBSERVATION_TYPE_ID) REFERENCES Observation_Type (OBSERVATION_TYPE_ID),
    FOREIGN KEY (OBSERVATION_CLUSTER_ID) REFERENCES Observation_Cluster (OBSERVATION_CLUSTER_ID)
);